---
apiVersion: v1
kind: ConfigMap
metadata:
  name: snt-config
  namespace: status-go-test
data:
  GITHUB_ORG: "status-im"
  GITHUB_REPO_SNTV2: "status-network-token-v2"
  GITHUB_REPO_COMMUNITIES: "communities-contracts"
---
apiVersion: v1
kind: Secret
metadata:
  name: snt-secrets
  namespace: status-go-test
type: Opaque
data:
  API_KEY_ETHERSCAN: ""
  API_KEY_ARBISCAN: ""
  API_KEY_OPTIMISTIC_ETHERSCAN: ""
  PRIVATE_KEY: "YWMwOTc0YmVjMzlhMTdlMzZiYTRhNmI0ZDIzOGZmOTQ0YmFjYjQ3OGNiZWQ1ZWZjYWU3ODRkN2JmNGYyZmY4MA=="